namespace dershaneOtomasyonu
{
    partial class PersonelEkrani
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PersonelEkrani));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle4 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle5 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle6 = new DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            DataGridViewCellStyle dataGridViewCellStyle7 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle8 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle9 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle10 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle11 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle12 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle13 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle14 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle15 = new DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            DataGridViewCellStyle dataGridViewCellStyle16 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle17 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle18 = new DataGridViewCellStyle();
            bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            label1 = new Label();
            CikisYap = new Button();
            bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            BtnGorusmePanel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            Btn_SiniflarVeOgrenciler = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            BtnistatislikPanel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            btnDersBaslatmaPanel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            BtnNotGondermePanel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            label2 = new Label();
            pictureBox1 = new PictureBox();
            Panel_SiniflarVeOgrenciler = new Bunifu.UI.WinForms.BunifuPanel();
            label32 = new Label();
            sinifinOgrencileriDataGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            label33 = new Label();
            siniflarDataGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            panelDosyaGonderme = new Bunifu.UI.WinForms.BunifuPanel();
            bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            Btn_YeniDosyaYukle = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            label4 = new Label();
            DosyaDataGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            label3 = new Label();
            SiniflarDosyaDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            panelDersBaslat = new Bunifu.UI.WinForms.BunifuPanel();
            label7 = new Label();
            label5 = new Label();
            chattingOgrDataGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            btnDersBaslat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            label6 = new Label();
            chattingSinifDataGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            bunifuGradientPanel1.SuspendLayout();
            bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox1).BeginInit();
            Panel_SiniflarVeOgrenciler.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)sinifinOgrencileriDataGridView).BeginInit();
            ((System.ComponentModel.ISupportInitialize)siniflarDataGridView).BeginInit();
            panelDosyaGonderme.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)DosyaDataGridView).BeginInit();
            ((System.ComponentModel.ISupportInitialize)SiniflarDosyaDataGridView1).BeginInit();
            panelDersBaslat.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)chattingOgrDataGridView).BeginInit();
            ((System.ComponentModel.ISupportInitialize)chattingSinifDataGridView).BeginInit();
            SuspendLayout();
            // 
            // bunifuGradientPanel1
            // 
            bunifuGradientPanel1.BackColor = Color.Transparent;
            bunifuGradientPanel1.BackgroundImage = (Image)resources.GetObject("bunifuGradientPanel1.BackgroundImage");
            bunifuGradientPanel1.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuGradientPanel1.BorderRadius = 1;
            bunifuGradientPanel1.Controls.Add(label1);
            bunifuGradientPanel1.Controls.Add(CikisYap);
            bunifuGradientPanel1.Dock = DockStyle.Top;
            bunifuGradientPanel1.GradientBottomLeft = Color.FromArgb(30, 24, 97);
            bunifuGradientPanel1.GradientBottomRight = SystemColors.Desktop;
            bunifuGradientPanel1.GradientTopLeft = Color.FromArgb(30, 24, 97);
            bunifuGradientPanel1.GradientTopRight = Color.FromArgb(30, 24, 60);
            bunifuGradientPanel1.Location = new Point(234, 0);
            bunifuGradientPanel1.Margin = new Padding(4);
            bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            bunifuGradientPanel1.Quality = 10;
            bunifuGradientPanel1.Size = new Size(1061, 73);
            bunifuGradientPanel1.TabIndex = 17;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("Century Gothic", 18F, FontStyle.Regular, GraphicsUnit.Point, 162);
            label1.ForeColor = SystemColors.Window;
            label1.Location = new Point(396, 18);
            label1.Name = "label1";
            label1.Size = new Size(193, 30);
            label1.TabIndex = 10;
            label1.Text = "Personel Paneli";
            // 
            // CikisYap
            // 
            CikisYap.BackColor = Color.Transparent;
            CikisYap.BackgroundImageLayout = ImageLayout.Zoom;
            CikisYap.Cursor = Cursors.Hand;
            CikisYap.FlatAppearance.BorderColor = SystemColors.Window;
            CikisYap.FlatAppearance.BorderSize = 0;
            CikisYap.FlatStyle = FlatStyle.Flat;
            CikisYap.Font = new Font("Century Gothic", 12F, FontStyle.Regular, GraphicsUnit.Point, 162);
            CikisYap.ForeColor = SystemColors.Window;
            CikisYap.Location = new Point(925, 13);
            CikisYap.Margin = new Padding(4);
            CikisYap.Name = "CikisYap";
            CikisYap.Size = new Size(116, 47);
            CikisYap.TabIndex = 9;
            CikisYap.Text = "Çıkış Yap";
            CikisYap.UseVisualStyleBackColor = false;
            CikisYap.Click += CikisYap_Click;
            // 
            // bunifuPanel1
            // 
            bunifuPanel1.BackgroundColor = Color.FromArgb(30, 24, 97);
            bunifuPanel1.BackgroundImage = (Image)resources.GetObject("bunifuPanel1.BackgroundImage");
            bunifuPanel1.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuPanel1.BorderColor = Color.Transparent;
            bunifuPanel1.BorderRadius = 0;
            bunifuPanel1.BorderThickness = 0;
            bunifuPanel1.Controls.Add(BtnGorusmePanel);
            bunifuPanel1.Controls.Add(Btn_SiniflarVeOgrenciler);
            bunifuPanel1.Controls.Add(BtnistatislikPanel);
            bunifuPanel1.Controls.Add(btnDersBaslatmaPanel);
            bunifuPanel1.Controls.Add(BtnNotGondermePanel);
            bunifuPanel1.Controls.Add(label2);
            bunifuPanel1.Controls.Add(pictureBox1);
            bunifuPanel1.Dock = DockStyle.Left;
            bunifuPanel1.Location = new Point(0, 0);
            bunifuPanel1.Margin = new Padding(4);
            bunifuPanel1.Name = "bunifuPanel1";
            bunifuPanel1.ShowBorders = true;
            bunifuPanel1.Size = new Size(234, 729);
            bunifuPanel1.TabIndex = 16;
            // 
            // BtnGorusmePanel
            // 
            BtnGorusmePanel.AllowAnimations = true;
            BtnGorusmePanel.AllowMouseEffects = true;
            BtnGorusmePanel.AllowToggling = false;
            BtnGorusmePanel.AnimationSpeed = 200;
            BtnGorusmePanel.AutoGenerateColors = false;
            BtnGorusmePanel.AutoRoundBorders = false;
            BtnGorusmePanel.AutoSizeLeftIcon = true;
            BtnGorusmePanel.AutoSizeRightIcon = true;
            BtnGorusmePanel.BackColor = Color.Transparent;
            BtnGorusmePanel.BackColor1 = Color.FromArgb(51, 122, 183);
            BtnGorusmePanel.BackgroundImage = (Image)resources.GetObject("BtnGorusmePanel.BackgroundImage");
            BtnGorusmePanel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnGorusmePanel.ButtonText = "Öğrenci Görüşme";
            BtnGorusmePanel.ButtonTextMarginLeft = 0;
            BtnGorusmePanel.ColorContrastOnClick = 45;
            BtnGorusmePanel.ColorContrastOnHover = 45;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            BtnGorusmePanel.CustomizableEdges = borderEdges1;
            BtnGorusmePanel.DialogResult = DialogResult.None;
            BtnGorusmePanel.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            BtnGorusmePanel.DisabledFillColor = Color.Empty;
            BtnGorusmePanel.DisabledForecolor = Color.Empty;
            BtnGorusmePanel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            BtnGorusmePanel.Font = new Font("Segoe UI", 9F);
            BtnGorusmePanel.ForeColor = Color.White;
            BtnGorusmePanel.IconLeft = null;
            BtnGorusmePanel.IconLeftAlign = ContentAlignment.MiddleLeft;
            BtnGorusmePanel.IconLeftCursor = Cursors.Default;
            BtnGorusmePanel.IconLeftPadding = new Padding(11, 3, 3, 3);
            BtnGorusmePanel.IconMarginLeft = 11;
            BtnGorusmePanel.IconPadding = 10;
            BtnGorusmePanel.IconRight = null;
            BtnGorusmePanel.IconRightAlign = ContentAlignment.MiddleRight;
            BtnGorusmePanel.IconRightCursor = Cursors.Default;
            BtnGorusmePanel.IconRightPadding = new Padding(3, 3, 7, 3);
            BtnGorusmePanel.IconSize = 25;
            BtnGorusmePanel.IdleBorderColor = Color.Empty;
            BtnGorusmePanel.IdleBorderRadius = 0;
            BtnGorusmePanel.IdleBorderThickness = 0;
            BtnGorusmePanel.IdleFillColor = Color.Empty;
            BtnGorusmePanel.IdleIconLeftImage = null;
            BtnGorusmePanel.IdleIconRightImage = null;
            BtnGorusmePanel.IndicateFocus = false;
            BtnGorusmePanel.Location = new Point(3, 424);
            BtnGorusmePanel.Name = "BtnGorusmePanel";
            BtnGorusmePanel.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            BtnGorusmePanel.OnDisabledState.BorderRadius = 1;
            BtnGorusmePanel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnGorusmePanel.OnDisabledState.BorderThickness = 1;
            BtnGorusmePanel.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            BtnGorusmePanel.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            BtnGorusmePanel.OnDisabledState.IconLeftImage = null;
            BtnGorusmePanel.OnDisabledState.IconRightImage = null;
            BtnGorusmePanel.onHoverState.BorderColor = Color.FromArgb(30, 24, 97);
            BtnGorusmePanel.onHoverState.BorderRadius = 1;
            BtnGorusmePanel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnGorusmePanel.onHoverState.BorderThickness = 1;
            BtnGorusmePanel.onHoverState.FillColor = Color.FromArgb(30, 24, 97);
            BtnGorusmePanel.onHoverState.ForeColor = Color.White;
            BtnGorusmePanel.onHoverState.IconLeftImage = null;
            BtnGorusmePanel.onHoverState.IconRightImage = null;
            BtnGorusmePanel.OnIdleState.BorderColor = Color.FromArgb(30, 24, 97);
            BtnGorusmePanel.OnIdleState.BorderRadius = 1;
            BtnGorusmePanel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnGorusmePanel.OnIdleState.BorderThickness = 1;
            BtnGorusmePanel.OnIdleState.FillColor = Color.FromArgb(30, 24, 97);
            BtnGorusmePanel.OnIdleState.ForeColor = Color.White;
            BtnGorusmePanel.OnIdleState.IconLeftImage = null;
            BtnGorusmePanel.OnIdleState.IconRightImage = null;
            BtnGorusmePanel.OnPressedState.BorderColor = Color.FromArgb(30, 24, 97);
            BtnGorusmePanel.OnPressedState.BorderRadius = 1;
            BtnGorusmePanel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnGorusmePanel.OnPressedState.BorderThickness = 1;
            BtnGorusmePanel.OnPressedState.FillColor = Color.FromArgb(30, 24, 90);
            BtnGorusmePanel.OnPressedState.ForeColor = Color.White;
            BtnGorusmePanel.OnPressedState.IconLeftImage = null;
            BtnGorusmePanel.OnPressedState.IconRightImage = null;
            BtnGorusmePanel.Size = new Size(234, 53);
            BtnGorusmePanel.TabIndex = 17;
            BtnGorusmePanel.TextAlign = ContentAlignment.MiddleCenter;
            BtnGorusmePanel.TextAlignment = HorizontalAlignment.Center;
            BtnGorusmePanel.TextMarginLeft = 0;
            BtnGorusmePanel.TextPadding = new Padding(0);
            BtnGorusmePanel.UseDefaultRadiusAndThickness = true;
            // 
            // Btn_SiniflarVeOgrenciler
            // 
            Btn_SiniflarVeOgrenciler.AllowAnimations = true;
            Btn_SiniflarVeOgrenciler.AllowMouseEffects = true;
            Btn_SiniflarVeOgrenciler.AllowToggling = false;
            Btn_SiniflarVeOgrenciler.AnimationSpeed = 200;
            Btn_SiniflarVeOgrenciler.AutoGenerateColors = false;
            Btn_SiniflarVeOgrenciler.AutoRoundBorders = false;
            Btn_SiniflarVeOgrenciler.AutoSizeLeftIcon = true;
            Btn_SiniflarVeOgrenciler.AutoSizeRightIcon = true;
            Btn_SiniflarVeOgrenciler.BackColor = Color.Transparent;
            Btn_SiniflarVeOgrenciler.BackColor1 = Color.FromArgb(51, 122, 183);
            Btn_SiniflarVeOgrenciler.BackgroundImage = (Image)resources.GetObject("Btn_SiniflarVeOgrenciler.BackgroundImage");
            Btn_SiniflarVeOgrenciler.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Btn_SiniflarVeOgrenciler.ButtonText = "Sınıflar ve Öğrenciler";
            Btn_SiniflarVeOgrenciler.ButtonTextMarginLeft = 0;
            Btn_SiniflarVeOgrenciler.ColorContrastOnClick = 45;
            Btn_SiniflarVeOgrenciler.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            Btn_SiniflarVeOgrenciler.CustomizableEdges = borderEdges2;
            Btn_SiniflarVeOgrenciler.DialogResult = DialogResult.None;
            Btn_SiniflarVeOgrenciler.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            Btn_SiniflarVeOgrenciler.DisabledFillColor = Color.Empty;
            Btn_SiniflarVeOgrenciler.DisabledForecolor = Color.Empty;
            Btn_SiniflarVeOgrenciler.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            Btn_SiniflarVeOgrenciler.Font = new Font("Segoe UI", 9F);
            Btn_SiniflarVeOgrenciler.ForeColor = Color.White;
            Btn_SiniflarVeOgrenciler.IconLeft = null;
            Btn_SiniflarVeOgrenciler.IconLeftAlign = ContentAlignment.MiddleLeft;
            Btn_SiniflarVeOgrenciler.IconLeftCursor = Cursors.Default;
            Btn_SiniflarVeOgrenciler.IconLeftPadding = new Padding(11, 3, 3, 3);
            Btn_SiniflarVeOgrenciler.IconMarginLeft = 11;
            Btn_SiniflarVeOgrenciler.IconPadding = 10;
            Btn_SiniflarVeOgrenciler.IconRight = null;
            Btn_SiniflarVeOgrenciler.IconRightAlign = ContentAlignment.MiddleRight;
            Btn_SiniflarVeOgrenciler.IconRightCursor = Cursors.Default;
            Btn_SiniflarVeOgrenciler.IconRightPadding = new Padding(3, 3, 7, 3);
            Btn_SiniflarVeOgrenciler.IconSize = 25;
            Btn_SiniflarVeOgrenciler.IdleBorderColor = Color.Empty;
            Btn_SiniflarVeOgrenciler.IdleBorderRadius = 0;
            Btn_SiniflarVeOgrenciler.IdleBorderThickness = 0;
            Btn_SiniflarVeOgrenciler.IdleFillColor = Color.Empty;
            Btn_SiniflarVeOgrenciler.IdleIconLeftImage = null;
            Btn_SiniflarVeOgrenciler.IdleIconRightImage = null;
            Btn_SiniflarVeOgrenciler.IndicateFocus = false;
            Btn_SiniflarVeOgrenciler.Location = new Point(0, 306);
            Btn_SiniflarVeOgrenciler.Name = "Btn_SiniflarVeOgrenciler";
            Btn_SiniflarVeOgrenciler.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            Btn_SiniflarVeOgrenciler.OnDisabledState.BorderRadius = 1;
            Btn_SiniflarVeOgrenciler.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Btn_SiniflarVeOgrenciler.OnDisabledState.BorderThickness = 1;
            Btn_SiniflarVeOgrenciler.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            Btn_SiniflarVeOgrenciler.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            Btn_SiniflarVeOgrenciler.OnDisabledState.IconLeftImage = null;
            Btn_SiniflarVeOgrenciler.OnDisabledState.IconRightImage = null;
            Btn_SiniflarVeOgrenciler.onHoverState.BorderColor = Color.FromArgb(30, 24, 97);
            Btn_SiniflarVeOgrenciler.onHoverState.BorderRadius = 1;
            Btn_SiniflarVeOgrenciler.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Btn_SiniflarVeOgrenciler.onHoverState.BorderThickness = 1;
            Btn_SiniflarVeOgrenciler.onHoverState.FillColor = Color.FromArgb(30, 24, 97);
            Btn_SiniflarVeOgrenciler.onHoverState.ForeColor = Color.White;
            Btn_SiniflarVeOgrenciler.onHoverState.IconLeftImage = null;
            Btn_SiniflarVeOgrenciler.onHoverState.IconRightImage = null;
            Btn_SiniflarVeOgrenciler.OnIdleState.BorderColor = Color.FromArgb(30, 24, 97);
            Btn_SiniflarVeOgrenciler.OnIdleState.BorderRadius = 1;
            Btn_SiniflarVeOgrenciler.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Btn_SiniflarVeOgrenciler.OnIdleState.BorderThickness = 1;
            Btn_SiniflarVeOgrenciler.OnIdleState.FillColor = Color.FromArgb(30, 24, 97);
            Btn_SiniflarVeOgrenciler.OnIdleState.ForeColor = Color.White;
            Btn_SiniflarVeOgrenciler.OnIdleState.IconLeftImage = null;
            Btn_SiniflarVeOgrenciler.OnIdleState.IconRightImage = null;
            Btn_SiniflarVeOgrenciler.OnPressedState.BorderColor = Color.FromArgb(30, 24, 97);
            Btn_SiniflarVeOgrenciler.OnPressedState.BorderRadius = 1;
            Btn_SiniflarVeOgrenciler.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Btn_SiniflarVeOgrenciler.OnPressedState.BorderThickness = 1;
            Btn_SiniflarVeOgrenciler.OnPressedState.FillColor = Color.FromArgb(30, 24, 90);
            Btn_SiniflarVeOgrenciler.OnPressedState.ForeColor = Color.White;
            Btn_SiniflarVeOgrenciler.OnPressedState.IconLeftImage = null;
            Btn_SiniflarVeOgrenciler.OnPressedState.IconRightImage = null;
            Btn_SiniflarVeOgrenciler.Size = new Size(234, 53);
            Btn_SiniflarVeOgrenciler.TabIndex = 16;
            Btn_SiniflarVeOgrenciler.TextAlign = ContentAlignment.MiddleCenter;
            Btn_SiniflarVeOgrenciler.TextAlignment = HorizontalAlignment.Center;
            Btn_SiniflarVeOgrenciler.TextMarginLeft = 0;
            Btn_SiniflarVeOgrenciler.TextPadding = new Padding(0);
            Btn_SiniflarVeOgrenciler.UseDefaultRadiusAndThickness = true;
            Btn_SiniflarVeOgrenciler.Click += Btn_SiniflarVeOgrenciler_Click;
            // 
            // BtnistatislikPanel
            // 
            BtnistatislikPanel.AllowAnimations = true;
            BtnistatislikPanel.AllowMouseEffects = true;
            BtnistatislikPanel.AllowToggling = false;
            BtnistatislikPanel.AnimationSpeed = 200;
            BtnistatislikPanel.AutoGenerateColors = false;
            BtnistatislikPanel.AutoRoundBorders = false;
            BtnistatislikPanel.AutoSizeLeftIcon = true;
            BtnistatislikPanel.AutoSizeRightIcon = true;
            BtnistatislikPanel.BackColor = Color.Transparent;
            BtnistatislikPanel.BackColor1 = Color.FromArgb(51, 122, 183);
            BtnistatislikPanel.BackgroundImage = (Image)resources.GetObject("BtnistatislikPanel.BackgroundImage");
            BtnistatislikPanel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnistatislikPanel.ButtonText = "Öğrenci Başarı Durumu";
            BtnistatislikPanel.ButtonTextMarginLeft = 0;
            BtnistatislikPanel.ColorContrastOnClick = 45;
            BtnistatislikPanel.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            BtnistatislikPanel.CustomizableEdges = borderEdges3;
            BtnistatislikPanel.DialogResult = DialogResult.None;
            BtnistatislikPanel.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            BtnistatislikPanel.DisabledFillColor = Color.Empty;
            BtnistatislikPanel.DisabledForecolor = Color.Empty;
            BtnistatislikPanel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            BtnistatislikPanel.Font = new Font("Segoe UI", 9F);
            BtnistatislikPanel.ForeColor = Color.White;
            BtnistatislikPanel.IconLeft = null;
            BtnistatislikPanel.IconLeftAlign = ContentAlignment.MiddleLeft;
            BtnistatislikPanel.IconLeftCursor = Cursors.Default;
            BtnistatislikPanel.IconLeftPadding = new Padding(11, 3, 3, 3);
            BtnistatislikPanel.IconMarginLeft = 11;
            BtnistatislikPanel.IconPadding = 10;
            BtnistatislikPanel.IconRight = null;
            BtnistatislikPanel.IconRightAlign = ContentAlignment.MiddleRight;
            BtnistatislikPanel.IconRightCursor = Cursors.Default;
            BtnistatislikPanel.IconRightPadding = new Padding(3, 3, 7, 3);
            BtnistatislikPanel.IconSize = 25;
            BtnistatislikPanel.IdleBorderColor = Color.Empty;
            BtnistatislikPanel.IdleBorderRadius = 0;
            BtnistatislikPanel.IdleBorderThickness = 0;
            BtnistatislikPanel.IdleFillColor = Color.Empty;
            BtnistatislikPanel.IdleIconLeftImage = null;
            BtnistatislikPanel.IdleIconRightImage = null;
            BtnistatislikPanel.IndicateFocus = false;
            BtnistatislikPanel.Location = new Point(0, 247);
            BtnistatislikPanel.Name = "BtnistatislikPanel";
            BtnistatislikPanel.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            BtnistatislikPanel.OnDisabledState.BorderRadius = 1;
            BtnistatislikPanel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnistatislikPanel.OnDisabledState.BorderThickness = 1;
            BtnistatislikPanel.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            BtnistatislikPanel.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            BtnistatislikPanel.OnDisabledState.IconLeftImage = null;
            BtnistatislikPanel.OnDisabledState.IconRightImage = null;
            BtnistatislikPanel.onHoverState.BorderColor = Color.FromArgb(30, 24, 97);
            BtnistatislikPanel.onHoverState.BorderRadius = 1;
            BtnistatislikPanel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnistatislikPanel.onHoverState.BorderThickness = 1;
            BtnistatislikPanel.onHoverState.FillColor = Color.FromArgb(30, 24, 97);
            BtnistatislikPanel.onHoverState.ForeColor = Color.White;
            BtnistatislikPanel.onHoverState.IconLeftImage = null;
            BtnistatislikPanel.onHoverState.IconRightImage = null;
            BtnistatislikPanel.OnIdleState.BorderColor = Color.FromArgb(30, 24, 97);
            BtnistatislikPanel.OnIdleState.BorderRadius = 1;
            BtnistatislikPanel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnistatislikPanel.OnIdleState.BorderThickness = 1;
            BtnistatislikPanel.OnIdleState.FillColor = Color.FromArgb(30, 24, 97);
            BtnistatislikPanel.OnIdleState.ForeColor = Color.White;
            BtnistatislikPanel.OnIdleState.IconLeftImage = null;
            BtnistatislikPanel.OnIdleState.IconRightImage = null;
            BtnistatislikPanel.OnPressedState.BorderColor = Color.FromArgb(30, 24, 97);
            BtnistatislikPanel.OnPressedState.BorderRadius = 1;
            BtnistatislikPanel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnistatislikPanel.OnPressedState.BorderThickness = 1;
            BtnistatislikPanel.OnPressedState.FillColor = Color.FromArgb(30, 24, 90);
            BtnistatislikPanel.OnPressedState.ForeColor = Color.White;
            BtnistatislikPanel.OnPressedState.IconLeftImage = null;
            BtnistatislikPanel.OnPressedState.IconRightImage = null;
            BtnistatislikPanel.Size = new Size(234, 53);
            BtnistatislikPanel.TabIndex = 15;
            BtnistatislikPanel.TextAlign = ContentAlignment.MiddleCenter;
            BtnistatislikPanel.TextAlignment = HorizontalAlignment.Center;
            BtnistatislikPanel.TextMarginLeft = 0;
            BtnistatislikPanel.TextPadding = new Padding(0);
            BtnistatislikPanel.UseDefaultRadiusAndThickness = true;
            // 
            // btnDersBaslatmaPanel
            // 
            btnDersBaslatmaPanel.AllowAnimations = true;
            btnDersBaslatmaPanel.AllowMouseEffects = true;
            btnDersBaslatmaPanel.AllowToggling = false;
            btnDersBaslatmaPanel.AnimationSpeed = 200;
            btnDersBaslatmaPanel.AutoGenerateColors = false;
            btnDersBaslatmaPanel.AutoRoundBorders = false;
            btnDersBaslatmaPanel.AutoSizeLeftIcon = true;
            btnDersBaslatmaPanel.AutoSizeRightIcon = true;
            btnDersBaslatmaPanel.BackColor = Color.Transparent;
            btnDersBaslatmaPanel.BackColor1 = Color.FromArgb(51, 122, 183);
            btnDersBaslatmaPanel.BackgroundImage = (Image)resources.GetObject("btnDersBaslatmaPanel.BackgroundImage");
            btnDersBaslatmaPanel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnDersBaslatmaPanel.ButtonText = "Derse Başla";
            btnDersBaslatmaPanel.ButtonTextMarginLeft = 0;
            btnDersBaslatmaPanel.ColorContrastOnClick = 45;
            btnDersBaslatmaPanel.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            btnDersBaslatmaPanel.CustomizableEdges = borderEdges4;
            btnDersBaslatmaPanel.DialogResult = DialogResult.None;
            btnDersBaslatmaPanel.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnDersBaslatmaPanel.DisabledFillColor = Color.Empty;
            btnDersBaslatmaPanel.DisabledForecolor = Color.Empty;
            btnDersBaslatmaPanel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            btnDersBaslatmaPanel.Font = new Font("Segoe UI", 9F);
            btnDersBaslatmaPanel.ForeColor = Color.White;
            btnDersBaslatmaPanel.IconLeft = null;
            btnDersBaslatmaPanel.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnDersBaslatmaPanel.IconLeftCursor = Cursors.Default;
            btnDersBaslatmaPanel.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnDersBaslatmaPanel.IconMarginLeft = 11;
            btnDersBaslatmaPanel.IconPadding = 10;
            btnDersBaslatmaPanel.IconRight = null;
            btnDersBaslatmaPanel.IconRightAlign = ContentAlignment.MiddleRight;
            btnDersBaslatmaPanel.IconRightCursor = Cursors.Default;
            btnDersBaslatmaPanel.IconRightPadding = new Padding(3, 3, 7, 3);
            btnDersBaslatmaPanel.IconSize = 25;
            btnDersBaslatmaPanel.IdleBorderColor = Color.Empty;
            btnDersBaslatmaPanel.IdleBorderRadius = 0;
            btnDersBaslatmaPanel.IdleBorderThickness = 0;
            btnDersBaslatmaPanel.IdleFillColor = Color.Empty;
            btnDersBaslatmaPanel.IdleIconLeftImage = null;
            btnDersBaslatmaPanel.IdleIconRightImage = null;
            btnDersBaslatmaPanel.IndicateFocus = false;
            btnDersBaslatmaPanel.Location = new Point(0, 365);
            btnDersBaslatmaPanel.Name = "btnDersBaslatmaPanel";
            btnDersBaslatmaPanel.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnDersBaslatmaPanel.OnDisabledState.BorderRadius = 1;
            btnDersBaslatmaPanel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnDersBaslatmaPanel.OnDisabledState.BorderThickness = 1;
            btnDersBaslatmaPanel.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnDersBaslatmaPanel.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnDersBaslatmaPanel.OnDisabledState.IconLeftImage = null;
            btnDersBaslatmaPanel.OnDisabledState.IconRightImage = null;
            btnDersBaslatmaPanel.onHoverState.BorderColor = Color.FromArgb(30, 24, 97);
            btnDersBaslatmaPanel.onHoverState.BorderRadius = 1;
            btnDersBaslatmaPanel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnDersBaslatmaPanel.onHoverState.BorderThickness = 1;
            btnDersBaslatmaPanel.onHoverState.FillColor = Color.FromArgb(30, 24, 97);
            btnDersBaslatmaPanel.onHoverState.ForeColor = Color.White;
            btnDersBaslatmaPanel.onHoverState.IconLeftImage = null;
            btnDersBaslatmaPanel.onHoverState.IconRightImage = null;
            btnDersBaslatmaPanel.OnIdleState.BorderColor = Color.FromArgb(30, 24, 97);
            btnDersBaslatmaPanel.OnIdleState.BorderRadius = 1;
            btnDersBaslatmaPanel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnDersBaslatmaPanel.OnIdleState.BorderThickness = 1;
            btnDersBaslatmaPanel.OnIdleState.FillColor = Color.FromArgb(30, 24, 97);
            btnDersBaslatmaPanel.OnIdleState.ForeColor = Color.White;
            btnDersBaslatmaPanel.OnIdleState.IconLeftImage = null;
            btnDersBaslatmaPanel.OnIdleState.IconRightImage = null;
            btnDersBaslatmaPanel.OnPressedState.BorderColor = Color.FromArgb(30, 24, 97);
            btnDersBaslatmaPanel.OnPressedState.BorderRadius = 1;
            btnDersBaslatmaPanel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnDersBaslatmaPanel.OnPressedState.BorderThickness = 1;
            btnDersBaslatmaPanel.OnPressedState.FillColor = Color.FromArgb(30, 24, 90);
            btnDersBaslatmaPanel.OnPressedState.ForeColor = Color.White;
            btnDersBaslatmaPanel.OnPressedState.IconLeftImage = null;
            btnDersBaslatmaPanel.OnPressedState.IconRightImage = null;
            btnDersBaslatmaPanel.Size = new Size(234, 53);
            btnDersBaslatmaPanel.TabIndex = 14;
            btnDersBaslatmaPanel.TextAlign = ContentAlignment.MiddleCenter;
            btnDersBaslatmaPanel.TextAlignment = HorizontalAlignment.Center;
            btnDersBaslatmaPanel.TextMarginLeft = 0;
            btnDersBaslatmaPanel.TextPadding = new Padding(0);
            btnDersBaslatmaPanel.UseDefaultRadiusAndThickness = true;
            btnDersBaslatmaPanel.Click += btnDersBaslatmaPanel_Click;
            // 
            // BtnNotGondermePanel
            // 
            BtnNotGondermePanel.AllowAnimations = true;
            BtnNotGondermePanel.AllowMouseEffects = true;
            BtnNotGondermePanel.AllowToggling = false;
            BtnNotGondermePanel.AnimationSpeed = 200;
            BtnNotGondermePanel.AutoGenerateColors = false;
            BtnNotGondermePanel.AutoRoundBorders = false;
            BtnNotGondermePanel.AutoSizeLeftIcon = true;
            BtnNotGondermePanel.AutoSizeRightIcon = true;
            BtnNotGondermePanel.BackColor = Color.Transparent;
            BtnNotGondermePanel.BackColor1 = Color.FromArgb(51, 122, 183);
            BtnNotGondermePanel.BackgroundImage = (Image)resources.GetObject("BtnNotGondermePanel.BackgroundImage");
            BtnNotGondermePanel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnNotGondermePanel.ButtonText = "Ders Notu Gönderme";
            BtnNotGondermePanel.ButtonTextMarginLeft = 0;
            BtnNotGondermePanel.ColorContrastOnClick = 45;
            BtnNotGondermePanel.ColorContrastOnHover = 45;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            BtnNotGondermePanel.CustomizableEdges = borderEdges5;
            BtnNotGondermePanel.DialogResult = DialogResult.None;
            BtnNotGondermePanel.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            BtnNotGondermePanel.DisabledFillColor = Color.Empty;
            BtnNotGondermePanel.DisabledForecolor = Color.Empty;
            BtnNotGondermePanel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            BtnNotGondermePanel.Font = new Font("Segoe UI", 9F);
            BtnNotGondermePanel.ForeColor = Color.White;
            BtnNotGondermePanel.IconLeft = null;
            BtnNotGondermePanel.IconLeftAlign = ContentAlignment.MiddleLeft;
            BtnNotGondermePanel.IconLeftCursor = Cursors.Default;
            BtnNotGondermePanel.IconLeftPadding = new Padding(11, 3, 3, 3);
            BtnNotGondermePanel.IconMarginLeft = 11;
            BtnNotGondermePanel.IconPadding = 10;
            BtnNotGondermePanel.IconRight = null;
            BtnNotGondermePanel.IconRightAlign = ContentAlignment.MiddleRight;
            BtnNotGondermePanel.IconRightCursor = Cursors.Default;
            BtnNotGondermePanel.IconRightPadding = new Padding(3, 3, 7, 3);
            BtnNotGondermePanel.IconSize = 25;
            BtnNotGondermePanel.IdleBorderColor = Color.Empty;
            BtnNotGondermePanel.IdleBorderRadius = 0;
            BtnNotGondermePanel.IdleBorderThickness = 0;
            BtnNotGondermePanel.IdleFillColor = Color.Empty;
            BtnNotGondermePanel.IdleIconLeftImage = null;
            BtnNotGondermePanel.IdleIconRightImage = null;
            BtnNotGondermePanel.IndicateFocus = false;
            BtnNotGondermePanel.Location = new Point(0, 188);
            BtnNotGondermePanel.Name = "BtnNotGondermePanel";
            BtnNotGondermePanel.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            BtnNotGondermePanel.OnDisabledState.BorderRadius = 1;
            BtnNotGondermePanel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnNotGondermePanel.OnDisabledState.BorderThickness = 1;
            BtnNotGondermePanel.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            BtnNotGondermePanel.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            BtnNotGondermePanel.OnDisabledState.IconLeftImage = null;
            BtnNotGondermePanel.OnDisabledState.IconRightImage = null;
            BtnNotGondermePanel.onHoverState.BorderColor = Color.FromArgb(30, 24, 97);
            BtnNotGondermePanel.onHoverState.BorderRadius = 1;
            BtnNotGondermePanel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnNotGondermePanel.onHoverState.BorderThickness = 1;
            BtnNotGondermePanel.onHoverState.FillColor = Color.FromArgb(30, 24, 97);
            BtnNotGondermePanel.onHoverState.ForeColor = Color.White;
            BtnNotGondermePanel.onHoverState.IconLeftImage = null;
            BtnNotGondermePanel.onHoverState.IconRightImage = null;
            BtnNotGondermePanel.OnIdleState.BorderColor = Color.FromArgb(30, 24, 97);
            BtnNotGondermePanel.OnIdleState.BorderRadius = 1;
            BtnNotGondermePanel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnNotGondermePanel.OnIdleState.BorderThickness = 1;
            BtnNotGondermePanel.OnIdleState.FillColor = Color.FromArgb(30, 24, 97);
            BtnNotGondermePanel.OnIdleState.ForeColor = Color.White;
            BtnNotGondermePanel.OnIdleState.IconLeftImage = null;
            BtnNotGondermePanel.OnIdleState.IconRightImage = null;
            BtnNotGondermePanel.OnPressedState.BorderColor = Color.FromArgb(30, 24, 97);
            BtnNotGondermePanel.OnPressedState.BorderRadius = 1;
            BtnNotGondermePanel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BtnNotGondermePanel.OnPressedState.BorderThickness = 1;
            BtnNotGondermePanel.OnPressedState.FillColor = Color.FromArgb(30, 24, 90);
            BtnNotGondermePanel.OnPressedState.ForeColor = Color.White;
            BtnNotGondermePanel.OnPressedState.IconLeftImage = null;
            BtnNotGondermePanel.OnPressedState.IconRightImage = null;
            BtnNotGondermePanel.Size = new Size(234, 53);
            BtnNotGondermePanel.TabIndex = 13;
            BtnNotGondermePanel.TextAlign = ContentAlignment.MiddleCenter;
            BtnNotGondermePanel.TextAlignment = HorizontalAlignment.Center;
            BtnNotGondermePanel.TextMarginLeft = 0;
            BtnNotGondermePanel.TextPadding = new Padding(0);
            BtnNotGondermePanel.UseDefaultRadiusAndThickness = true;
            BtnNotGondermePanel.Click += BtnNotGondermePanel_Click;
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.BackColor = Color.Transparent;
            label2.Font = new Font("Century Gothic", 14.25F, FontStyle.Regular, GraphicsUnit.Point, 162);
            label2.ForeColor = SystemColors.Window;
            label2.Location = new Point(8, 109);
            label2.Name = "label2";
            label2.Size = new Size(223, 22);
            label2.TabIndex = 11;
            label2.Text = "Dershane Otomasyonu";
            // 
            // pictureBox1
            // 
            pictureBox1.BackColor = Color.Transparent;
            pictureBox1.Cursor = Cursors.Hand;
            pictureBox1.Image = (Image)resources.GetObject("pictureBox1.Image");
            pictureBox1.Location = new Point(72, 18);
            pictureBox1.Name = "pictureBox1";
            pictureBox1.Size = new Size(81, 78);
            pictureBox1.SizeMode = PictureBoxSizeMode.StretchImage;
            pictureBox1.TabIndex = 12;
            pictureBox1.TabStop = false;
            pictureBox1.Click += pictureBox1_Click;
            // 
            // Panel_SiniflarVeOgrenciler
            // 
            Panel_SiniflarVeOgrenciler.BackgroundColor = Color.Transparent;
            Panel_SiniflarVeOgrenciler.BackgroundImage = (Image)resources.GetObject("Panel_SiniflarVeOgrenciler.BackgroundImage");
            Panel_SiniflarVeOgrenciler.BackgroundImageLayout = ImageLayout.Stretch;
            Panel_SiniflarVeOgrenciler.BorderColor = Color.Transparent;
            Panel_SiniflarVeOgrenciler.BorderRadius = 3;
            Panel_SiniflarVeOgrenciler.BorderThickness = 1;
            Panel_SiniflarVeOgrenciler.Controls.Add(label32);
            Panel_SiniflarVeOgrenciler.Controls.Add(sinifinOgrencileriDataGridView);
            Panel_SiniflarVeOgrenciler.Controls.Add(label33);
            Panel_SiniflarVeOgrenciler.Controls.Add(siniflarDataGridView);
            Panel_SiniflarVeOgrenciler.Location = new Point(240, 80);
            Panel_SiniflarVeOgrenciler.Name = "Panel_SiniflarVeOgrenciler";
            Panel_SiniflarVeOgrenciler.ShowBorders = true;
            Panel_SiniflarVeOgrenciler.Size = new Size(1050, 640);
            Panel_SiniflarVeOgrenciler.TabIndex = 18;
            Panel_SiniflarVeOgrenciler.Visible = false;
            // 
            // label32
            // 
            label32.AutoSize = true;
            label32.BackColor = Color.Transparent;
            label32.Font = new Font("Century Gothic", 14.25F, FontStyle.Regular, GraphicsUnit.Point, 162);
            label32.ForeColor = SystemColors.MenuText;
            label32.Location = new Point(532, 15);
            label32.Name = "label32";
            label32.Size = new Size(106, 22);
            label32.TabIndex = 36;
            label32.Text = "Öğrenciler";
            // 
            // sinifinOgrencileriDataGridView
            // 
            sinifinOgrencileriDataGridView.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = Color.FromArgb(248, 251, 255);
            dataGridViewCellStyle1.ForeColor = Color.Black;
            sinifinOgrencileriDataGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            sinifinOgrencileriDataGridView.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            sinifinOgrencileriDataGridView.BorderStyle = BorderStyle.None;
            sinifinOgrencileriDataGridView.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            sinifinOgrencileriDataGridView.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = Color.White;
            dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(24, 115, 204);
            dataGridViewCellStyle2.SelectionForeColor = Color.White;
            dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
            sinifinOgrencileriDataGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            sinifinOgrencileriDataGridView.ColumnHeadersHeight = 40;
            sinifinOgrencileriDataGridView.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
            sinifinOgrencileriDataGridView.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            sinifinOgrencileriDataGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            sinifinOgrencileriDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            sinifinOgrencileriDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            sinifinOgrencileriDataGridView.CurrentTheme.BackColor = Color.White;
            sinifinOgrencileriDataGridView.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
            sinifinOgrencileriDataGridView.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
            sinifinOgrencileriDataGridView.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            sinifinOgrencileriDataGridView.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            sinifinOgrencileriDataGridView.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
            sinifinOgrencileriDataGridView.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            sinifinOgrencileriDataGridView.CurrentTheme.Name = null;
            sinifinOgrencileriDataGridView.CurrentTheme.RowsStyle.BackColor = Color.White;
            sinifinOgrencileriDataGridView.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            sinifinOgrencileriDataGridView.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            sinifinOgrencileriDataGridView.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            sinifinOgrencileriDataGridView.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = Color.White;
            dataGridViewCellStyle3.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dataGridViewCellStyle3.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
            sinifinOgrencileriDataGridView.DefaultCellStyle = dataGridViewCellStyle3;
            sinifinOgrencileriDataGridView.EnableHeadersVisualStyles = false;
            sinifinOgrencileriDataGridView.GridColor = Color.FromArgb(221, 238, 255);
            sinifinOgrencileriDataGridView.HeaderBackColor = Color.DodgerBlue;
            sinifinOgrencileriDataGridView.HeaderBgColor = Color.Empty;
            sinifinOgrencileriDataGridView.HeaderForeColor = Color.White;
            sinifinOgrencileriDataGridView.Location = new Point(532, 49);
            sinifinOgrencileriDataGridView.Name = "sinifinOgrencileriDataGridView";
            sinifinOgrencileriDataGridView.ReadOnly = true;
            sinifinOgrencileriDataGridView.RowHeadersVisible = false;
            sinifinOgrencileriDataGridView.RowTemplate.Height = 40;
            sinifinOgrencileriDataGridView.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            sinifinOgrencileriDataGridView.Size = new Size(490, 584);
            sinifinOgrencileriDataGridView.TabIndex = 35;
            sinifinOgrencileriDataGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // label33
            // 
            label33.AutoSize = true;
            label33.BackColor = Color.Transparent;
            label33.Font = new Font("Century Gothic", 14.25F, FontStyle.Regular, GraphicsUnit.Point, 162);
            label33.ForeColor = SystemColors.MenuText;
            label33.Location = new Point(17, 15);
            label33.Name = "label33";
            label33.Size = new Size(65, 22);
            label33.TabIndex = 34;
            label33.Text = "Sınıflar";
            // 
            // siniflarDataGridView
            // 
            siniflarDataGridView.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = Color.FromArgb(248, 251, 255);
            dataGridViewCellStyle4.ForeColor = Color.Black;
            siniflarDataGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            siniflarDataGridView.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            siniflarDataGridView.BorderStyle = BorderStyle.None;
            siniflarDataGridView.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            siniflarDataGridView.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = Color.White;
            dataGridViewCellStyle5.SelectionBackColor = Color.FromArgb(24, 115, 204);
            dataGridViewCellStyle5.SelectionForeColor = Color.White;
            dataGridViewCellStyle5.WrapMode = DataGridViewTriState.True;
            siniflarDataGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            siniflarDataGridView.ColumnHeadersHeight = 40;
            siniflarDataGridView.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
            siniflarDataGridView.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            siniflarDataGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            siniflarDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            siniflarDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            siniflarDataGridView.CurrentTheme.BackColor = Color.White;
            siniflarDataGridView.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
            siniflarDataGridView.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
            siniflarDataGridView.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            siniflarDataGridView.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            siniflarDataGridView.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
            siniflarDataGridView.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            siniflarDataGridView.CurrentTheme.Name = null;
            siniflarDataGridView.CurrentTheme.RowsStyle.BackColor = Color.White;
            siniflarDataGridView.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            siniflarDataGridView.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            siniflarDataGridView.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            siniflarDataGridView.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle6.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = Color.White;
            dataGridViewCellStyle6.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dataGridViewCellStyle6.SelectionForeColor = Color.Black;
            dataGridViewCellStyle6.WrapMode = DataGridViewTriState.False;
            siniflarDataGridView.DefaultCellStyle = dataGridViewCellStyle6;
            siniflarDataGridView.EnableHeadersVisualStyles = false;
            siniflarDataGridView.GridColor = Color.FromArgb(221, 238, 255);
            siniflarDataGridView.HeaderBackColor = Color.DodgerBlue;
            siniflarDataGridView.HeaderBgColor = Color.Empty;
            siniflarDataGridView.HeaderForeColor = Color.White;
            siniflarDataGridView.Location = new Point(17, 49);
            siniflarDataGridView.Name = "siniflarDataGridView";
            siniflarDataGridView.ReadOnly = true;
            siniflarDataGridView.RowHeadersVisible = false;
            siniflarDataGridView.RowTemplate.Height = 40;
            siniflarDataGridView.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            siniflarDataGridView.Size = new Size(490, 584);
            siniflarDataGridView.TabIndex = 33;
            siniflarDataGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            siniflarDataGridView.MouseClick += siniflarDataGridView_MouseClick;
            // 
            // panelDosyaGonderme
            // 
            panelDosyaGonderme.BackgroundColor = Color.Transparent;
            panelDosyaGonderme.BackgroundImage = (Image)resources.GetObject("panelDosyaGonderme.BackgroundImage");
            panelDosyaGonderme.BackgroundImageLayout = ImageLayout.Stretch;
            panelDosyaGonderme.BorderColor = Color.Transparent;
            panelDosyaGonderme.BorderRadius = 3;
            panelDosyaGonderme.BorderThickness = 1;
            panelDosyaGonderme.Controls.Add(bunifuButton1);
            panelDosyaGonderme.Controls.Add(Btn_YeniDosyaYukle);
            panelDosyaGonderme.Controls.Add(label4);
            panelDosyaGonderme.Controls.Add(DosyaDataGridView);
            panelDosyaGonderme.Controls.Add(label3);
            panelDosyaGonderme.Controls.Add(SiniflarDosyaDataGridView1);
            panelDosyaGonderme.Location = new Point(240, 80);
            panelDosyaGonderme.Name = "panelDosyaGonderme";
            panelDosyaGonderme.ShowBorders = true;
            panelDosyaGonderme.Size = new Size(1050, 640);
            panelDosyaGonderme.TabIndex = 37;
            panelDosyaGonderme.Visible = false;
            // 
            // bunifuButton1
            // 
            bunifuButton1.AllowAnimations = true;
            bunifuButton1.AllowMouseEffects = true;
            bunifuButton1.AllowToggling = false;
            bunifuButton1.AnimationSpeed = 200;
            bunifuButton1.AutoGenerateColors = false;
            bunifuButton1.AutoRoundBorders = false;
            bunifuButton1.AutoSizeLeftIcon = true;
            bunifuButton1.AutoSizeRightIcon = true;
            bunifuButton1.BackColor = Color.Transparent;
            bunifuButton1.BackColor1 = Color.FromArgb(51, 122, 183);
            bunifuButton1.BackgroundImage = (Image)resources.GetObject("bunifuButton1.BackgroundImage");
            bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton1.ButtonText = "Seçimi Temizle";
            bunifuButton1.ButtonTextMarginLeft = 0;
            bunifuButton1.ColorContrastOnClick = 45;
            bunifuButton1.ColorContrastOnHover = 45;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            bunifuButton1.CustomizableEdges = borderEdges6;
            bunifuButton1.DialogResult = DialogResult.None;
            bunifuButton1.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton1.DisabledFillColor = Color.Empty;
            bunifuButton1.DisabledForecolor = Color.Empty;
            bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            bunifuButton1.Font = new Font("Segoe UI", 9F);
            bunifuButton1.ForeColor = Color.White;
            bunifuButton1.IconLeft = null;
            bunifuButton1.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton1.IconLeftCursor = Cursors.Default;
            bunifuButton1.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton1.IconMarginLeft = 11;
            bunifuButton1.IconPadding = 10;
            bunifuButton1.IconRight = null;
            bunifuButton1.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton1.IconRightCursor = Cursors.Default;
            bunifuButton1.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton1.IconSize = 25;
            bunifuButton1.IdleBorderColor = Color.Empty;
            bunifuButton1.IdleBorderRadius = 0;
            bunifuButton1.IdleBorderThickness = 0;
            bunifuButton1.IdleFillColor = Color.Empty;
            bunifuButton1.IdleIconLeftImage = null;
            bunifuButton1.IdleIconRightImage = null;
            bunifuButton1.IndicateFocus = false;
            bunifuButton1.Location = new Point(17, 574);
            bunifuButton1.Name = "bunifuButton1";
            bunifuButton1.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton1.OnDisabledState.BorderRadius = 1;
            bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton1.OnDisabledState.BorderThickness = 1;
            bunifuButton1.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton1.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton1.OnDisabledState.IconLeftImage = null;
            bunifuButton1.OnDisabledState.IconRightImage = null;
            bunifuButton1.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
            bunifuButton1.onHoverState.BorderRadius = 1;
            bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton1.onHoverState.BorderThickness = 1;
            bunifuButton1.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
            bunifuButton1.onHoverState.ForeColor = Color.White;
            bunifuButton1.onHoverState.IconLeftImage = null;
            bunifuButton1.onHoverState.IconRightImage = null;
            bunifuButton1.OnIdleState.BorderColor = Color.FromArgb(255, 128, 0);
            bunifuButton1.OnIdleState.BorderRadius = 1;
            bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton1.OnIdleState.BorderThickness = 1;
            bunifuButton1.OnIdleState.FillColor = Color.FromArgb(255, 128, 0);
            bunifuButton1.OnIdleState.ForeColor = Color.White;
            bunifuButton1.OnIdleState.IconLeftImage = null;
            bunifuButton1.OnIdleState.IconRightImage = null;
            bunifuButton1.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bunifuButton1.OnPressedState.BorderRadius = 1;
            bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton1.OnPressedState.BorderThickness = 1;
            bunifuButton1.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bunifuButton1.OnPressedState.ForeColor = Color.White;
            bunifuButton1.OnPressedState.IconLeftImage = null;
            bunifuButton1.OnPressedState.IconRightImage = null;
            bunifuButton1.Size = new Size(257, 39);
            bunifuButton1.TabIndex = 36;
            bunifuButton1.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton1.TextAlignment = HorizontalAlignment.Center;
            bunifuButton1.TextMarginLeft = 0;
            bunifuButton1.TextPadding = new Padding(0);
            bunifuButton1.UseDefaultRadiusAndThickness = true;
            bunifuButton1.Click += bunifuButton1_Click;
            // 
            // Btn_YeniDosyaYukle
            // 
            Btn_YeniDosyaYukle.AllowAnimations = true;
            Btn_YeniDosyaYukle.AllowMouseEffects = true;
            Btn_YeniDosyaYukle.AllowToggling = false;
            Btn_YeniDosyaYukle.AnimationSpeed = 200;
            Btn_YeniDosyaYukle.AutoGenerateColors = false;
            Btn_YeniDosyaYukle.AutoRoundBorders = false;
            Btn_YeniDosyaYukle.AutoSizeLeftIcon = true;
            Btn_YeniDosyaYukle.AutoSizeRightIcon = true;
            Btn_YeniDosyaYukle.BackColor = Color.Transparent;
            Btn_YeniDosyaYukle.BackColor1 = Color.FromArgb(51, 122, 183);
            Btn_YeniDosyaYukle.BackgroundImage = (Image)resources.GetObject("Btn_YeniDosyaYukle.BackgroundImage");
            Btn_YeniDosyaYukle.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Btn_YeniDosyaYukle.ButtonText = "Yeni Dosya Yükle";
            Btn_YeniDosyaYukle.ButtonTextMarginLeft = 0;
            Btn_YeniDosyaYukle.ColorContrastOnClick = 45;
            Btn_YeniDosyaYukle.ColorContrastOnHover = 45;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            Btn_YeniDosyaYukle.CustomizableEdges = borderEdges7;
            Btn_YeniDosyaYukle.DialogResult = DialogResult.None;
            Btn_YeniDosyaYukle.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            Btn_YeniDosyaYukle.DisabledFillColor = Color.Empty;
            Btn_YeniDosyaYukle.DisabledForecolor = Color.Empty;
            Btn_YeniDosyaYukle.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            Btn_YeniDosyaYukle.Font = new Font("Segoe UI", 9F);
            Btn_YeniDosyaYukle.ForeColor = Color.White;
            Btn_YeniDosyaYukle.IconLeft = null;
            Btn_YeniDosyaYukle.IconLeftAlign = ContentAlignment.MiddleLeft;
            Btn_YeniDosyaYukle.IconLeftCursor = Cursors.Default;
            Btn_YeniDosyaYukle.IconLeftPadding = new Padding(11, 3, 3, 3);
            Btn_YeniDosyaYukle.IconMarginLeft = 11;
            Btn_YeniDosyaYukle.IconPadding = 10;
            Btn_YeniDosyaYukle.IconRight = null;
            Btn_YeniDosyaYukle.IconRightAlign = ContentAlignment.MiddleRight;
            Btn_YeniDosyaYukle.IconRightCursor = Cursors.Default;
            Btn_YeniDosyaYukle.IconRightPadding = new Padding(3, 3, 7, 3);
            Btn_YeniDosyaYukle.IconSize = 25;
            Btn_YeniDosyaYukle.IdleBorderColor = Color.Empty;
            Btn_YeniDosyaYukle.IdleBorderRadius = 0;
            Btn_YeniDosyaYukle.IdleBorderThickness = 0;
            Btn_YeniDosyaYukle.IdleFillColor = Color.Empty;
            Btn_YeniDosyaYukle.IdleIconLeftImage = null;
            Btn_YeniDosyaYukle.IdleIconRightImage = null;
            Btn_YeniDosyaYukle.IndicateFocus = false;
            Btn_YeniDosyaYukle.Location = new Point(577, 563);
            Btn_YeniDosyaYukle.Name = "Btn_YeniDosyaYukle";
            Btn_YeniDosyaYukle.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            Btn_YeniDosyaYukle.OnDisabledState.BorderRadius = 1;
            Btn_YeniDosyaYukle.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Btn_YeniDosyaYukle.OnDisabledState.BorderThickness = 1;
            Btn_YeniDosyaYukle.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            Btn_YeniDosyaYukle.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            Btn_YeniDosyaYukle.OnDisabledState.IconLeftImage = null;
            Btn_YeniDosyaYukle.OnDisabledState.IconRightImage = null;
            Btn_YeniDosyaYukle.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
            Btn_YeniDosyaYukle.onHoverState.BorderRadius = 1;
            Btn_YeniDosyaYukle.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Btn_YeniDosyaYukle.onHoverState.BorderThickness = 1;
            Btn_YeniDosyaYukle.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
            Btn_YeniDosyaYukle.onHoverState.ForeColor = Color.White;
            Btn_YeniDosyaYukle.onHoverState.IconLeftImage = null;
            Btn_YeniDosyaYukle.onHoverState.IconRightImage = null;
            Btn_YeniDosyaYukle.OnIdleState.BorderColor = Color.DodgerBlue;
            Btn_YeniDosyaYukle.OnIdleState.BorderRadius = 1;
            Btn_YeniDosyaYukle.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Btn_YeniDosyaYukle.OnIdleState.BorderThickness = 1;
            Btn_YeniDosyaYukle.OnIdleState.FillColor = Color.DodgerBlue;
            Btn_YeniDosyaYukle.OnIdleState.ForeColor = Color.White;
            Btn_YeniDosyaYukle.OnIdleState.IconLeftImage = null;
            Btn_YeniDosyaYukle.OnIdleState.IconRightImage = null;
            Btn_YeniDosyaYukle.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            Btn_YeniDosyaYukle.OnPressedState.BorderRadius = 1;
            Btn_YeniDosyaYukle.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Btn_YeniDosyaYukle.OnPressedState.BorderThickness = 1;
            Btn_YeniDosyaYukle.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            Btn_YeniDosyaYukle.OnPressedState.ForeColor = Color.White;
            Btn_YeniDosyaYukle.OnPressedState.IconLeftImage = null;
            Btn_YeniDosyaYukle.OnPressedState.IconRightImage = null;
            Btn_YeniDosyaYukle.Size = new Size(150, 39);
            Btn_YeniDosyaYukle.TabIndex = 35;
            Btn_YeniDosyaYukle.TextAlign = ContentAlignment.MiddleCenter;
            Btn_YeniDosyaYukle.TextAlignment = HorizontalAlignment.Center;
            Btn_YeniDosyaYukle.TextMarginLeft = 0;
            Btn_YeniDosyaYukle.TextPadding = new Padding(0);
            Btn_YeniDosyaYukle.UseDefaultRadiusAndThickness = true;
            Btn_YeniDosyaYukle.Click += Btn_YeniDosyaYukle_Click;
            // 
            // label4
            // 
            label4.AutoSize = true;
            label4.BackColor = Color.Transparent;
            label4.Font = new Font("Century Gothic", 14.25F, FontStyle.Regular, GraphicsUnit.Point, 162);
            label4.ForeColor = SystemColors.MenuText;
            label4.Location = new Point(300, 15);
            label4.Name = "label4";
            label4.Size = new Size(142, 22);
            label4.TabIndex = 34;
            label4.Text = "Yüklü Dosyalar";
            // 
            // DosyaDataGridView
            // 
            DosyaDataGridView.AllowCustomTheming = false;
            DosyaDataGridView.AllowUserToAddRows = false;
            dataGridViewCellStyle7.BackColor = Color.FromArgb(248, 251, 255);
            dataGridViewCellStyle7.ForeColor = Color.Black;
            DosyaDataGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle7;
            DosyaDataGridView.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            DosyaDataGridView.BorderStyle = BorderStyle.None;
            DosyaDataGridView.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            DosyaDataGridView.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle8.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle8.BackColor = Color.DodgerBlue;
            dataGridViewCellStyle8.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dataGridViewCellStyle8.ForeColor = Color.White;
            dataGridViewCellStyle8.SelectionBackColor = Color.FromArgb(24, 115, 204);
            dataGridViewCellStyle8.SelectionForeColor = Color.White;
            dataGridViewCellStyle8.WrapMode = DataGridViewTriState.True;
            DosyaDataGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle8;
            DosyaDataGridView.ColumnHeadersHeight = 40;
            DosyaDataGridView.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
            DosyaDataGridView.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            DosyaDataGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            DosyaDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            DosyaDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            DosyaDataGridView.CurrentTheme.BackColor = Color.White;
            DosyaDataGridView.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
            DosyaDataGridView.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
            DosyaDataGridView.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            DosyaDataGridView.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            DosyaDataGridView.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
            DosyaDataGridView.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            DosyaDataGridView.CurrentTheme.Name = null;
            DosyaDataGridView.CurrentTheme.RowsStyle.BackColor = Color.White;
            DosyaDataGridView.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            DosyaDataGridView.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            DosyaDataGridView.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            DosyaDataGridView.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle9.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle9.BackColor = Color.White;
            dataGridViewCellStyle9.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle9.ForeColor = Color.Black;
            dataGridViewCellStyle9.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dataGridViewCellStyle9.SelectionForeColor = Color.Black;
            dataGridViewCellStyle9.WrapMode = DataGridViewTriState.False;
            DosyaDataGridView.DefaultCellStyle = dataGridViewCellStyle9;
            DosyaDataGridView.EnableHeadersVisualStyles = false;
            DosyaDataGridView.GridColor = Color.FromArgb(221, 238, 255);
            DosyaDataGridView.HeaderBackColor = Color.DodgerBlue;
            DosyaDataGridView.HeaderBgColor = Color.Empty;
            DosyaDataGridView.HeaderForeColor = Color.White;
            DosyaDataGridView.Location = new Point(300, 49);
            DosyaDataGridView.Name = "DosyaDataGridView";
            DosyaDataGridView.ReadOnly = true;
            DosyaDataGridView.RowHeadersVisible = false;
            DosyaDataGridView.RowTemplate.Height = 40;
            DosyaDataGridView.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            DosyaDataGridView.Size = new Size(722, 488);
            DosyaDataGridView.TabIndex = 33;
            DosyaDataGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            DosyaDataGridView.CellClick += DosyaDataGridView_CellClick;
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.BackColor = Color.Transparent;
            label3.Font = new Font("Century Gothic", 14.25F, FontStyle.Regular, GraphicsUnit.Point, 162);
            label3.ForeColor = SystemColors.MenuText;
            label3.Location = new Point(17, 15);
            label3.Name = "label3";
            label3.Size = new Size(65, 22);
            label3.TabIndex = 32;
            label3.Text = "Sınıflar";
            // 
            // SiniflarDosyaDataGridView1
            // 
            SiniflarDosyaDataGridView1.AllowCustomTheming = false;
            dataGridViewCellStyle10.BackColor = Color.FromArgb(248, 251, 255);
            dataGridViewCellStyle10.ForeColor = Color.Black;
            SiniflarDosyaDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle10;
            SiniflarDosyaDataGridView1.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            SiniflarDosyaDataGridView1.BorderStyle = BorderStyle.None;
            SiniflarDosyaDataGridView1.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            SiniflarDosyaDataGridView1.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle11.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle11.BackColor = Color.DodgerBlue;
            dataGridViewCellStyle11.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dataGridViewCellStyle11.ForeColor = Color.White;
            dataGridViewCellStyle11.SelectionBackColor = Color.FromArgb(24, 115, 204);
            dataGridViewCellStyle11.SelectionForeColor = Color.White;
            dataGridViewCellStyle11.WrapMode = DataGridViewTriState.True;
            SiniflarDosyaDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle11;
            SiniflarDosyaDataGridView1.ColumnHeadersHeight = 40;
            SiniflarDosyaDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
            SiniflarDosyaDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            SiniflarDosyaDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            SiniflarDosyaDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            SiniflarDosyaDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            SiniflarDosyaDataGridView1.CurrentTheme.BackColor = Color.White;
            SiniflarDosyaDataGridView1.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
            SiniflarDosyaDataGridView1.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
            SiniflarDosyaDataGridView1.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            SiniflarDosyaDataGridView1.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            SiniflarDosyaDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
            SiniflarDosyaDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            SiniflarDosyaDataGridView1.CurrentTheme.Name = null;
            SiniflarDosyaDataGridView1.CurrentTheme.RowsStyle.BackColor = Color.White;
            SiniflarDosyaDataGridView1.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            SiniflarDosyaDataGridView1.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            SiniflarDosyaDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            SiniflarDosyaDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle12.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle12.BackColor = Color.White;
            dataGridViewCellStyle12.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle12.ForeColor = Color.Black;
            dataGridViewCellStyle12.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dataGridViewCellStyle12.SelectionForeColor = Color.Black;
            dataGridViewCellStyle12.WrapMode = DataGridViewTriState.False;
            SiniflarDosyaDataGridView1.DefaultCellStyle = dataGridViewCellStyle12;
            SiniflarDosyaDataGridView1.EnableHeadersVisualStyles = false;
            SiniflarDosyaDataGridView1.GridColor = Color.FromArgb(221, 238, 255);
            SiniflarDosyaDataGridView1.HeaderBackColor = Color.DodgerBlue;
            SiniflarDosyaDataGridView1.HeaderBgColor = Color.Empty;
            SiniflarDosyaDataGridView1.HeaderForeColor = Color.White;
            SiniflarDosyaDataGridView1.Location = new Point(17, 49);
            SiniflarDosyaDataGridView1.Name = "SiniflarDosyaDataGridView1";
            SiniflarDosyaDataGridView1.ReadOnly = true;
            SiniflarDosyaDataGridView1.RowHeadersVisible = false;
            SiniflarDosyaDataGridView1.RowTemplate.Height = 40;
            SiniflarDosyaDataGridView1.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            SiniflarDosyaDataGridView1.Size = new Size(257, 519);
            SiniflarDosyaDataGridView1.TabIndex = 31;
            SiniflarDosyaDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // panelDersBaslat
            // 
            panelDersBaslat.BackgroundColor = Color.Transparent;
            panelDersBaslat.BackgroundImage = (Image)resources.GetObject("panelDersBaslat.BackgroundImage");
            panelDersBaslat.BackgroundImageLayout = ImageLayout.Stretch;
            panelDersBaslat.BorderColor = Color.Transparent;
            panelDersBaslat.BorderRadius = 3;
            panelDersBaslat.BorderThickness = 1;
            panelDersBaslat.Controls.Add(label7);
            panelDersBaslat.Controls.Add(label5);
            panelDersBaslat.Controls.Add(chattingOgrDataGridView);
            panelDersBaslat.Controls.Add(btnDersBaslat);
            panelDersBaslat.Controls.Add(label6);
            panelDersBaslat.Controls.Add(chattingSinifDataGridView);
            panelDersBaslat.Location = new Point(241, 80);
            panelDersBaslat.Name = "panelDersBaslat";
            panelDersBaslat.ShowBorders = true;
            panelDersBaslat.Size = new Size(1050, 640);
            panelDersBaslat.TabIndex = 38;
            panelDersBaslat.Visible = false;
            // 
            // label7
            // 
            label7.BackColor = Color.Transparent;
            label7.Font = new Font("Century Gothic", 14.25F, FontStyle.Regular, GraphicsUnit.Point, 162);
            label7.ForeColor = SystemColors.MenuText;
            label7.Location = new Point(664, 367);
            label7.Name = "label7";
            label7.Size = new Size(273, 81);
            label7.TabIndex = 38;
            label7.Text = "Dikkat: Ders başlatıldığında öğrencilerkonuşma odasına bağlanabilecekler.";
            // 
            // label5
            // 
            label5.AutoSize = true;
            label5.BackColor = Color.Transparent;
            label5.Font = new Font("Century Gothic", 14.25F, FontStyle.Regular, GraphicsUnit.Point, 162);
            label5.ForeColor = SystemColors.MenuText;
            label5.Location = new Point(347, 123);
            label5.Name = "label5";
            label5.Size = new Size(106, 22);
            label5.TabIndex = 37;
            label5.Text = "Öğrenciler";
            // 
            // chattingOgrDataGridView
            // 
            chattingOgrDataGridView.AllowCustomTheming = false;
            dataGridViewCellStyle13.BackColor = Color.FromArgb(248, 251, 255);
            dataGridViewCellStyle13.ForeColor = Color.Black;
            chattingOgrDataGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle13;
            chattingOgrDataGridView.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            chattingOgrDataGridView.BorderStyle = BorderStyle.None;
            chattingOgrDataGridView.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            chattingOgrDataGridView.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle14.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle14.BackColor = Color.DodgerBlue;
            dataGridViewCellStyle14.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dataGridViewCellStyle14.ForeColor = Color.White;
            dataGridViewCellStyle14.SelectionBackColor = Color.FromArgb(24, 115, 204);
            dataGridViewCellStyle14.SelectionForeColor = Color.White;
            dataGridViewCellStyle14.WrapMode = DataGridViewTriState.True;
            chattingOgrDataGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle14;
            chattingOgrDataGridView.ColumnHeadersHeight = 40;
            chattingOgrDataGridView.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
            chattingOgrDataGridView.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            chattingOgrDataGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            chattingOgrDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            chattingOgrDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            chattingOgrDataGridView.CurrentTheme.BackColor = Color.White;
            chattingOgrDataGridView.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
            chattingOgrDataGridView.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
            chattingOgrDataGridView.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            chattingOgrDataGridView.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            chattingOgrDataGridView.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
            chattingOgrDataGridView.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            chattingOgrDataGridView.CurrentTheme.Name = null;
            chattingOgrDataGridView.CurrentTheme.RowsStyle.BackColor = Color.White;
            chattingOgrDataGridView.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            chattingOgrDataGridView.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            chattingOgrDataGridView.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            chattingOgrDataGridView.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle15.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle15.BackColor = Color.White;
            dataGridViewCellStyle15.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle15.ForeColor = Color.Black;
            dataGridViewCellStyle15.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dataGridViewCellStyle15.SelectionForeColor = Color.Black;
            dataGridViewCellStyle15.WrapMode = DataGridViewTriState.False;
            chattingOgrDataGridView.DefaultCellStyle = dataGridViewCellStyle15;
            chattingOgrDataGridView.EnableHeadersVisualStyles = false;
            chattingOgrDataGridView.GridColor = Color.FromArgb(221, 238, 255);
            chattingOgrDataGridView.HeaderBackColor = Color.DodgerBlue;
            chattingOgrDataGridView.HeaderBgColor = Color.Empty;
            chattingOgrDataGridView.HeaderForeColor = Color.White;
            chattingOgrDataGridView.Location = new Point(347, 157);
            chattingOgrDataGridView.Name = "chattingOgrDataGridView";
            chattingOgrDataGridView.ReadOnly = true;
            chattingOgrDataGridView.RowHeadersVisible = false;
            chattingOgrDataGridView.RowTemplate.Height = 40;
            chattingOgrDataGridView.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            chattingOgrDataGridView.Size = new Size(257, 348);
            chattingOgrDataGridView.TabIndex = 36;
            chattingOgrDataGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // btnDersBaslat
            // 
            btnDersBaslat.AllowAnimations = true;
            btnDersBaslat.AllowMouseEffects = true;
            btnDersBaslat.AllowToggling = false;
            btnDersBaslat.AnimationSpeed = 200;
            btnDersBaslat.AutoGenerateColors = false;
            btnDersBaslat.AutoRoundBorders = false;
            btnDersBaslat.AutoSizeLeftIcon = true;
            btnDersBaslat.AutoSizeRightIcon = true;
            btnDersBaslat.BackColor = Color.Transparent;
            btnDersBaslat.BackColor1 = Color.FromArgb(51, 122, 183);
            btnDersBaslat.BackgroundImage = (Image)resources.GetObject("btnDersBaslat.BackgroundImage");
            btnDersBaslat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnDersBaslat.ButtonText = "Dersi Başlat";
            btnDersBaslat.ButtonTextMarginLeft = 0;
            btnDersBaslat.ColorContrastOnClick = 45;
            btnDersBaslat.ColorContrastOnHover = 45;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            btnDersBaslat.CustomizableEdges = borderEdges8;
            btnDersBaslat.DialogResult = DialogResult.None;
            btnDersBaslat.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnDersBaslat.DisabledFillColor = Color.Empty;
            btnDersBaslat.DisabledForecolor = Color.Empty;
            btnDersBaslat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            btnDersBaslat.Font = new Font("Segoe UI", 9F);
            btnDersBaslat.ForeColor = Color.White;
            btnDersBaslat.IconLeft = null;
            btnDersBaslat.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnDersBaslat.IconLeftCursor = Cursors.Default;
            btnDersBaslat.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnDersBaslat.IconMarginLeft = 11;
            btnDersBaslat.IconPadding = 10;
            btnDersBaslat.IconRight = null;
            btnDersBaslat.IconRightAlign = ContentAlignment.MiddleRight;
            btnDersBaslat.IconRightCursor = Cursors.Default;
            btnDersBaslat.IconRightPadding = new Padding(3, 3, 7, 3);
            btnDersBaslat.IconSize = 25;
            btnDersBaslat.IdleBorderColor = Color.Empty;
            btnDersBaslat.IdleBorderRadius = 0;
            btnDersBaslat.IdleBorderThickness = 0;
            btnDersBaslat.IdleFillColor = Color.Empty;
            btnDersBaslat.IdleIconLeftImage = null;
            btnDersBaslat.IdleIconRightImage = null;
            btnDersBaslat.IndicateFocus = false;
            btnDersBaslat.Location = new Point(725, 240);
            btnDersBaslat.Name = "btnDersBaslat";
            btnDersBaslat.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnDersBaslat.OnDisabledState.BorderRadius = 1;
            btnDersBaslat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnDersBaslat.OnDisabledState.BorderThickness = 1;
            btnDersBaslat.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnDersBaslat.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnDersBaslat.OnDisabledState.IconLeftImage = null;
            btnDersBaslat.OnDisabledState.IconRightImage = null;
            btnDersBaslat.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
            btnDersBaslat.onHoverState.BorderRadius = 1;
            btnDersBaslat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnDersBaslat.onHoverState.BorderThickness = 1;
            btnDersBaslat.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
            btnDersBaslat.onHoverState.ForeColor = Color.White;
            btnDersBaslat.onHoverState.IconLeftImage = null;
            btnDersBaslat.onHoverState.IconRightImage = null;
            btnDersBaslat.OnIdleState.BorderColor = Color.DodgerBlue;
            btnDersBaslat.OnIdleState.BorderRadius = 1;
            btnDersBaslat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnDersBaslat.OnIdleState.BorderThickness = 1;
            btnDersBaslat.OnIdleState.FillColor = Color.DodgerBlue;
            btnDersBaslat.OnIdleState.ForeColor = Color.White;
            btnDersBaslat.OnIdleState.IconLeftImage = null;
            btnDersBaslat.OnIdleState.IconRightImage = null;
            btnDersBaslat.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnDersBaslat.OnPressedState.BorderRadius = 1;
            btnDersBaslat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnDersBaslat.OnPressedState.BorderThickness = 1;
            btnDersBaslat.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnDersBaslat.OnPressedState.ForeColor = Color.White;
            btnDersBaslat.OnPressedState.IconLeftImage = null;
            btnDersBaslat.OnPressedState.IconRightImage = null;
            btnDersBaslat.Size = new Size(150, 39);
            btnDersBaslat.TabIndex = 35;
            btnDersBaslat.TextAlign = ContentAlignment.MiddleCenter;
            btnDersBaslat.TextAlignment = HorizontalAlignment.Center;
            btnDersBaslat.TextMarginLeft = 0;
            btnDersBaslat.TextPadding = new Padding(0);
            btnDersBaslat.UseDefaultRadiusAndThickness = true;
            btnDersBaslat.Click += btnDersBaslat_Click;
            // 
            // label6
            // 
            label6.AutoSize = true;
            label6.BackColor = Color.Transparent;
            label6.Font = new Font("Century Gothic", 14.25F, FontStyle.Regular, GraphicsUnit.Point, 162);
            label6.ForeColor = SystemColors.MenuText;
            label6.Location = new Point(65, 123);
            label6.Name = "label6";
            label6.Size = new Size(65, 22);
            label6.TabIndex = 32;
            label6.Text = "Sınıflar";
            // 
            // chattingSinifDataGridView
            // 
            chattingSinifDataGridView.AllowCustomTheming = false;
            dataGridViewCellStyle16.BackColor = Color.FromArgb(248, 251, 255);
            dataGridViewCellStyle16.ForeColor = Color.Black;
            chattingSinifDataGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle16;
            chattingSinifDataGridView.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            chattingSinifDataGridView.BorderStyle = BorderStyle.None;
            chattingSinifDataGridView.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            chattingSinifDataGridView.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle17.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle17.BackColor = Color.DodgerBlue;
            dataGridViewCellStyle17.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dataGridViewCellStyle17.ForeColor = Color.White;
            dataGridViewCellStyle17.SelectionBackColor = Color.FromArgb(24, 115, 204);
            dataGridViewCellStyle17.SelectionForeColor = Color.White;
            dataGridViewCellStyle17.WrapMode = DataGridViewTriState.True;
            chattingSinifDataGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle17;
            chattingSinifDataGridView.ColumnHeadersHeight = 40;
            chattingSinifDataGridView.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
            chattingSinifDataGridView.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            chattingSinifDataGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            chattingSinifDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            chattingSinifDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            chattingSinifDataGridView.CurrentTheme.BackColor = Color.White;
            chattingSinifDataGridView.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
            chattingSinifDataGridView.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
            chattingSinifDataGridView.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            chattingSinifDataGridView.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            chattingSinifDataGridView.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
            chattingSinifDataGridView.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            chattingSinifDataGridView.CurrentTheme.Name = null;
            chattingSinifDataGridView.CurrentTheme.RowsStyle.BackColor = Color.White;
            chattingSinifDataGridView.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            chattingSinifDataGridView.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            chattingSinifDataGridView.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            chattingSinifDataGridView.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle18.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle18.BackColor = Color.White;
            dataGridViewCellStyle18.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle18.ForeColor = Color.Black;
            dataGridViewCellStyle18.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dataGridViewCellStyle18.SelectionForeColor = Color.Black;
            dataGridViewCellStyle18.WrapMode = DataGridViewTriState.False;
            chattingSinifDataGridView.DefaultCellStyle = dataGridViewCellStyle18;
            chattingSinifDataGridView.EnableHeadersVisualStyles = false;
            chattingSinifDataGridView.GridColor = Color.FromArgb(221, 238, 255);
            chattingSinifDataGridView.HeaderBackColor = Color.DodgerBlue;
            chattingSinifDataGridView.HeaderBgColor = Color.Empty;
            chattingSinifDataGridView.HeaderForeColor = Color.White;
            chattingSinifDataGridView.Location = new Point(65, 157);
            chattingSinifDataGridView.Name = "chattingSinifDataGridView";
            chattingSinifDataGridView.ReadOnly = true;
            chattingSinifDataGridView.RowHeadersVisible = false;
            chattingSinifDataGridView.RowTemplate.Height = 40;
            chattingSinifDataGridView.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            chattingSinifDataGridView.Size = new Size(257, 348);
            chattingSinifDataGridView.TabIndex = 31;
            chattingSinifDataGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            chattingSinifDataGridView.MouseClick += chattingSinifDataGridView_MouseClick;
            // 
            // PersonelEkrani
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1295, 729);
            Controls.Add(panelDersBaslat);
            Controls.Add(panelDosyaGonderme);
            Controls.Add(Panel_SiniflarVeOgrenciler);
            Controls.Add(bunifuGradientPanel1);
            Controls.Add(bunifuPanel1);
            Name = "PersonelEkrani";
            Text = "Form4";
            Load += Form4_Load;
            bunifuGradientPanel1.ResumeLayout(false);
            bunifuGradientPanel1.PerformLayout();
            bunifuPanel1.ResumeLayout(false);
            bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox1).EndInit();
            Panel_SiniflarVeOgrenciler.ResumeLayout(false);
            Panel_SiniflarVeOgrenciler.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)sinifinOgrencileriDataGridView).EndInit();
            ((System.ComponentModel.ISupportInitialize)siniflarDataGridView).EndInit();
            panelDosyaGonderme.ResumeLayout(false);
            panelDosyaGonderme.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)DosyaDataGridView).EndInit();
            ((System.ComponentModel.ISupportInitialize)SiniflarDosyaDataGridView1).EndInit();
            panelDersBaslat.ResumeLayout(false);
            panelDersBaslat.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)chattingOgrDataGridView).EndInit();
            ((System.ComponentModel.ISupportInitialize)chattingSinifDataGridView).EndInit();
            ResumeLayout(false);
        }

        #endregion
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Label label1;
        private Button CikisYap;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnGorusmePanel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Btn_SiniflarVeOgrenciler;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnistatislikPanel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDersBaslatmaPanel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnNotGondermePanel;
        private Label label2;
        private PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuPanel Panel_SiniflarVeOgrenciler;
        private Label label32;
        private Bunifu.UI.WinForms.BunifuDataGridView sinifinOgrencileriDataGridView;
        private Label label33;
        private Bunifu.UI.WinForms.BunifuDataGridView siniflarDataGridView;
        private Bunifu.UI.WinForms.BunifuPanel panelDosyaGonderme;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Btn_YeniDosyaYukle;
        private Label label4;
        private Bunifu.UI.WinForms.BunifuDataGridView DosyaDataGridView;
        private Label label3;
        private Bunifu.UI.WinForms.BunifuDataGridView SiniflarDosyaDataGridView1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuPanel panelDersBaslat;
        private Label label5;
        private Bunifu.UI.WinForms.BunifuDataGridView chattingOgrDataGridView;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDersBaslat;
        private Label label6;
        private Bunifu.UI.WinForms.BunifuDataGridView chattingSinifDataGridView;
        private Label label7;
    }
}